version: 0.0
os: linux

files:
  - source: /
    destination: /var/my-node-app

hooks:
   ApplicationStart:
    - location: /var/my-node-app/app.js
      timeout: 300
      runas: root
      commands:
        - pm2 start app.js
