version: 0.0
os: linux

files:
  - source: /
    destination: /root/Nodejs_deployement_new_cicd/node_deployment

hooks:
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300

