version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  build:
    commands:
      # Add your build commands here if needed

  post_build:
    commands:
      - pm2 start app.js

artifacts:
  files:
    - '**/*'
