version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    pre_build:
      commands:
        - echo Installing source node dependencies...
        - cd /root/Nodejs_deployement_new_cicd/node_deployment
        - npm install
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      # Start the application using PM2
        - pm2 start /root/Nodejs_deployement_new_cicd/node_deployment/app.js
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  name: 'my-nodejs-app-artifact'  # Replace 'my-nodejs-app-artifact' with your desired artifact name
